remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
title: Madeline's Portfolio
author: Madeline Overton
email: mnoverton987@gmail.com
description: Past and Current Astronomy work
home_url: moverton000.github.io/madelineoverton.github.io/